namespace FS.Charts

open Fable.Core

[<RequireQualifiedAccess>]
type Interop =
    static member inline mkProperty<'ControlProperty> (key: string) (value: obj) : 'ControlProperty = unbox (key, value)

type [<Erase>] IAreaChartProp = interface end
type [<Erase>] IMarginProp = interface end
type [<Erase>] ISecondaryYScaleOptionProp = interface end
type [<Erase>] ILegendPropProp = interface end
type [<Erase>] ILegendProp = interface end
type [<Erase>] ILegendsStylesProp = interface end
type [<Erase>] IDateTimeFormatOptionsProp = interface end
type [<Erase>] ITimeLocaleDefinitionProp = interface end
type [<Erase>] ICartesianChartStylesProp = interface end
type [<Erase>] IChartPopoverProp = interface end
type [<Erase>] IYValueHoverProp = interface end
type [<Erase>] IAccessibilityProp = interface end
type [<Erase>] IPopoverComponentStylesProp = interface end
type [<Erase>] IChartPropProp = interface end
type [<Erase>] ILineChartProp = interface end
type [<Erase>] IDonutChartProp = interface end
type [<Erase>] IFunnelChartProp = interface end
type [<Erase>] IGaugeChartProp = interface end
type [<Erase>] IGanttChartProp = interface end
type [<Erase>] IScatterChartProp = interface end
type [<Erase>] IHeatMapChartProp = interface end
type [<Erase>] ISankeyChartProp = interface end
type [<Erase>] ISparklineProp = interface end
type [<Erase>] IGroupedVerticalBarChartProp = interface end
type [<Erase>] IHorizontalBarChartProp = interface end
type [<Erase>] IHorizontalBarChartWithAxisProp = interface end
type [<Erase>] IVerticalBarChartProp = interface end
type [<Erase>] IVerticalStackedBarChartProp = interface end
type [<Erase>] IChartTableProp = interface end
type [<Erase>] IChartDataPointProp = interface end
type [<Erase>] IHorizontalDataPointProp = interface end
type [<Erase>] ILineChartPointsProp = interface end
type [<Erase>] ILineChartDataPointProp = interface end
type [<Erase>] IBaseDataPointProp = interface end
type [<Erase>] IScatterChartDataPointProp = interface end
type [<Erase>] ILineChartGapProp = interface end
type [<Erase>] ILineChartLineOptionsProp = interface end
type [<Erase>] IScatterChartPointsProp = interface end
type [<Erase>] ISankeyChartDataProp = interface end
type [<Erase>] ISankeyChartPointProp = interface end
type [<Erase>] ISNodeProp = interface end
type [<Erase>] ISLinkProp = interface end
type [<Erase>] IChartTableHeaderProp = interface end
type [<Erase>] IChartTableRowProp = interface end
type [<Erase>] IChartTableStylesProp = interface end
type [<Erase>] IDonutChartStylesProp = interface end
type [<Erase>] IFunnelChartDataPointProp = interface end
type [<Erase>] IFunnelChartDataPointSubValueProp = interface end
type [<Erase>] IFunnelChartStylesProp = interface end
type [<Erase>] IGanttChartDataPointProp = interface end
type [<Erase>] IXDataPointProp = interface end
type [<Erase>] IGaugeChartSegmentProp = interface end
type [<Erase>] IGaugeChartStylesProp = interface end
type [<Erase>] IGroupedVerticalBarChartStylesProp = interface end
type [<Erase>] IGroupedVerticalBarChartDataProp = interface end
type [<Erase>] IGVBarChartSeriesPointProp = interface end
type [<Erase>] IHeatMapChartDataProp = interface end
type [<Erase>] IHeatMapChartDataPointProp = interface end
type [<Erase>] IHeatMapChartStylesProp = interface end
type [<Erase>] IChartDataModeProp = interface end
type [<Erase>] IHorizontalBarChartStylesProp = interface end
type [<Erase>] IHorizontalBarChartVariantProp = interface end

// ---------
type [<Erase>] ILegendShape = interface end
type [<Erase>] IMargins = interface end
type [<Erase>] ICartesianChartStyleProps = interface end
type [<Erase>] ILineChartProps = interface end
type [<Erase>] ILineChartDataProp = interface end
type [<Erase>] ILineChartLineOptions = interface end
type [<Erase>] ILineChartStyles = interface end
type [<Erase>] IAreaChartDataProp = interface end
type [<Erase>] IDonutChartProps = interface end
type [<Erase>] IChartDataPoint = interface end
type [<Erase>] IFunnelChartProps = interface end
type [<Erase>] IGaugeChartSegment = interface end
type [<Erase>] IGaugeChartStyles = interface end
type [<Erase>] IScatterChartProps = interface end
type [<Erase>] IScatterChartPoints = interface end
type [<Erase>] IScatterChartStyles = interface end
type [<Erase>] ISankeyChartProps = interface end
type [<Erase>] ISankeyChartAccessibility = interface end
type [<Erase>] ISparklineProps = interface end
type [<Erase>] IVerticalBarChartProps = interface end
type [<Erase>] IVerticalBarChartDataPoint = interface end
type [<Erase>] IVerticalBarChartStyles = interface end
type [<Erase>] IVerticalStackedBarChartProps = interface end
type [<Erase>] IVerticalStackedChartProps = interface end
type [<Erase>] IVSChartDataPoint = interface end
type [<Erase>] ILineDataInVerticalStackedBarChart = interface end
type [<Erase>] IVerticalStackedBarChartStyles = interface end
type [<Erase>] IChartTableProps = interface end
type [<Erase>] IChartTableDataProps = interface end

